version: "3.0"
services:
    fitness-ui:
        image: castab/fitness-ui:local
        ports:
            - "3000:3000"

    fitness-backend:
        image: castab/fitness-backend:local
        ports:
            - "8080:8080"

    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongoadmin
            MONGO_INITDB_ROOT_PASSWORD: mongopassword