version: "3.0"
services:
    # Comment out the fitness-ui service to test active development work
    fitness-ui:
        image: castab/fitness-ui:local
        ports:
            - "3000:3000"

    fitness-backend:
        image: castab/fitness-backend:local
        environment:
            - MONGO_URI=mongodb://fitness_service:fitness_password@mongo/fitness_log
        ports:
            - "8080:8080"

    mongo:
        image: mongo
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js