version: "3.0"
services:
    fitness-backend:
        image: castab/fitness-backend:local
        environment:
            - MONGO_URI=mongodb://fitness_service:fitness_password@mongo/fitness_log
        ports:
            - "8080:8080"

    mongo:
        image: mongo
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js